"""Factory sounds. Engines: 0 = analog, 1 = FM, 2 = electric piano."""

PRESETS = [
    {
        "name": "Dream Pad",
        "synth": {"engine": 0, "attack": 0.6, "decay": 1.5, "sustain": 0.8, "release": 1.8,
                  "cutoff": 1400, "resonance": 0.2, "fenv_amount": 1.0, "fenv_decay": 1.5,
                  "detune": 12, "osc2": 0.9, "sub": 0.2, "lfo_rate": 0.4, "lfo_cutoff": 0.3,
                  "vibrato": 4, "gain": 0.18},
        "fx": {"chorus_mix": 0.6, "delay_mix": 0.15, "reverb_mix": 0.45, "reverb_size": 0.9},
    },
    {
        "name": "Tine Keys",
        "synth": {"engine": 2, "attack": 0.002, "decay": 2.5, "sustain": 0.0, "release": 0.35,
                  "cutoff": 9000, "fm_index": 1.6, "fm_sustain_index": 0.3, "fm_decay": 0.8,
                  "tine": 0.5, "tremolo": 0.25, "lfo_rate": 4.5, "velocity_sens": 0.8,
                  "gain": 0.3},
        "fx": {"chorus_mix": 0.3, "reverb_mix": 0.25},
    },
    {
        "name": "Warm Poly",
        "synth": {"engine": 0, "attack": 0.01, "decay": 0.8, "sustain": 0.55, "release": 0.5,
                  "cutoff": 900, "resonance": 0.35, "fenv_amount": 2.5, "fenv_decay": 0.6,
                  "detune": 9, "osc2": 0.8, "shape": 0.3, "vibrato": 3, "lfo_rate": 5.5,
                  "gain": 0.22},
        "fx": {"chorus_mix": 0.7, "delay_mix": 0.2, "reverb_mix": 0.3, "drive": 0.2},
    },
    {
        "name": "Glass Bell",
        "synth": {"engine": 1, "attack": 0.002, "decay": 3.0, "sustain": 0.0, "release": 1.2,
                  "cutoff": 12000, "fm_ratio": 3.5, "fm_index": 3.0, "fm_sustain_index": 0.4,
                  "fm_decay": 1.0, "gain": 0.22},
        "fx": {"chorus_mix": 0.2, "delay_mix": 0.25, "reverb_mix": 0.4},
    },
    {
        "name": "Soft Brass",
        "synth": {"engine": 0, "attack": 0.08, "decay": 0.6, "sustain": 0.75, "release": 0.3,
                  "cutoff": 700, "resonance": 0.15, "fenv_amount": 2.8, "fenv_decay": 0.35,
                  "detune": 6, "osc2": 0.8, "gain": 0.22},
        "fx": {"chorus_mix": 0.3, "reverb_mix": 0.25},
    },
    {
        "name": "String Machine",
        "synth": {"engine": 0, "attack": 0.35, "decay": 1.0, "sustain": 0.9, "release": 1.0,
                  "cutoff": 3200, "resonance": 0.05, "detune": 18, "osc2": 1.0,
                  "vibrato": 6, "lfo_rate": 5.0, "gain": 0.16},
        "fx": {"chorus_mix": 0.9, "chorus_depth": 5.0, "reverb_mix": 0.4},
    },
    {
        "name": "Pluck",
        "synth": {"engine": 0, "attack": 0.001, "decay": 0.35, "sustain": 0.0, "release": 0.3,
                  "cutoff": 500, "resonance": 0.4, "fenv_amount": 4.0, "fenv_decay": 0.18,
                  "detune": 5, "osc2": 0.6, "shape": 0.5, "gain": 0.3},
        "fx": {"chorus_mix": 0.3, "delay_mix": 0.3, "reverb_mix": 0.3},
    },
    {
        "name": "FM Organ",
        "synth": {"engine": 1, "attack": 0.005, "decay": 0.2, "sustain": 1.0, "release": 0.08,
                  "cutoff": 8000, "fm_ratio": 2.0, "fm_index": 0.9, "fm_sustain_index": 0.9,
                  "tremolo": 0.15, "lfo_rate": 6.5, "velocity_sens": 0.0, "gain": 0.2},
        "fx": {"chorus_mix": 0.8, "reverb_mix": 0.2, "drive": 0.3},
    },
    {
        "name": "Velvet EP",
        "synth": {"engine": 2, "attack": 0.003, "decay": 3.5, "sustain": 0.1, "release": 0.5,
                  "cutoff": 3500, "fm_index": 0.9, "fm_sustain_index": 0.15, "fm_decay": 1.2,
                  "tine": 0.25, "tremolo": 0.4, "lfo_rate": 3.5, "gain": 0.32},
        "fx": {"chorus_mix": 0.5, "delay_mix": 0.1, "reverb_mix": 0.3, "drive": 0.15},
    },
    {
        "name": "Wobble Choir",
        "synth": {"engine": 0, "attack": 0.4, "decay": 1.0, "sustain": 0.85, "release": 1.2,
                  "cutoff": 1100, "resonance": 0.5, "detune": 14, "osc2": 1.0, "shape": 0.6,
                  "lfo_rate": 0.25, "lfo_cutoff": 0.8, "vibrato": 8, "gain": 0.17},
        "fx": {"chorus_mix": 0.6, "delay_mix": 0.2, "reverb_mix": 0.55, "reverb_size": 1.0},
    },
]

BASS_PRESETS = [
    {"name": "Sub", "synth": {"engine": 0, "attack": 0.005, "decay": 0.4, "sustain": 0.9,
                              "release": 0.15, "cutoff": 400, "osc2": 0.0, "sub": 0.9,
                              "shape": 0.0, "keytrack": 0.5, "gain": 0.45}},
    {"name": "Round", "synth": {"engine": 0, "attack": 0.003, "decay": 0.5, "sustain": 0.6,
                                "release": 0.15, "cutoff": 300, "resonance": 0.3,
                                "fenv_amount": 2.5, "fenv_decay": 0.25, "osc2": 0.5,
                                "detune": 4, "sub": 0.4, "keytrack": 0.6, "gain": 0.4}},
    {"name": "FM Bass", "synth": {"engine": 1, "attack": 0.002, "decay": 0.6, "sustain": 0.5,
                                  "release": 0.12, "cutoff": 2500, "fm_ratio": 1.0,
                                  "fm_index": 2.5, "fm_sustain_index": 0.6, "fm_decay": 0.25,
                                  "gain": 0.4}},
    {"name": "Square", "synth": {"engine": 0, "attack": 0.003, "decay": 0.3, "sustain": 0.7,
                                 "release": 0.1, "cutoff": 900, "resonance": 0.2,
                                 "fenv_amount": 1.5, "fenv_decay": 0.15, "shape": 1.0,
                                 "osc2": 0.0, "sub": 0.3, "keytrack": 0.6, "gain": 0.32}},
]
